services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: warm_up_api_development
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    volumes:
      - .:/app
    ports:
      - "3100:3000"
    depends_on:
      - db

volumes:
  db-data: